// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'featured.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Featured _$FeaturedFromJson(Map<String, dynamic> json) {
  return Featured(
    id: json['id'] as String?,
    id_poi: json['id_poi'] as String?,
    cat_convenzioni: json['cat_convenzioni'] as String?,
    cat_areesosta: json['cat_areesosta'] as String?,
    cat_areeservizio: json['cat_areeservizio'] as String?,
    cat_camping: json['cat_camping'] as String?,
    cat_attrazioni: json['cat_attrazioni'] as String?,
    cat_allianz: json['cat_allianz'] as String?,
    id_tipologia_poi: json['id_tipologia_poi'] as String?,
    id_localita_poi: json['id_localita_poi'] as String?,
    nome_poi: json['nome_poi'] as String?,
    indirizzo_poi: json['indirizzo_poi'] as String?,
    citta_poi: json['citta_poi'] as String?,
    cap_poi: json['cap_poi'] as String?,
    provincia_poi: json['provincia_poi'] as String?,
    regione_poi: json['regione_poi'] as String?,
    nazione_poi: json['nazione_poi'] as String?,
    telefono_poi: json['telefono_poi'] as String?,
    fax_poi: json['fax_poi'] as String?,
    email_poi: json['email_poi'] as String?,
    sitoweb_poi: json['sitoweb_poi'] as String?,
    paginafb_poi: json['paginafb_poi'] as String?,
    scadenza_conv_poi: json['scadenza_conv_poi'] as String?,
    lat_poi: json['lat_poi'] as String?,
    lon_poi: json['lon_poi'] as String?,
    precisionegeo_poi: json['precisionegeo_poi'] as String?,
    quota_poi: json['quota_poi'] as String?,
    id_parchi_poi: json['id_parchi_poi'] as String?,
    apertodal_poi: json['apertodal_poi'] as String?,
    apertoal_poi: json['apertoal_poi'] as String?,
    facilitazioni_poi: json['facilitazioni_poi'] as String?,
    sconto_poi: json['sconto_poi'] as String?,
    sconto_poi_en: json['sconto_poi_en'] as String?,
    referenti_poi: json['referenti_poi'] as String?,
    desc_poi: json['desc_poi'] as String?,
    desc_poi_en: json['desc_poi_en'] as String?,
    numeroposti_poi: json['numeroposti_poi'] as String?,
    tariffagiorno_poi: json['tariffagiorno_poi'] as String?,
    idsAmbienti_poi: json['idsAmbienti_poi'] as String?,
    idsServizi_poi: json['idsServizi_poi'] as String?,
    maxgiorni_poi: json['maxgiorni_poi'] as String?,
    piazzola_poi: json['piazzola_poi'] as String?,
    attrazioni_poi: json['attrazioni_poi'] as String?,
    no_gps: json['no_gps'] as String?,
    offline: json['offline'] as String?,
    rev_en: json['rev_en'] as String?,
  );
}

Map<String, dynamic> _$FeaturedToJson(Featured instance) => <String, dynamic>{
      'id': instance.id,
      'id_poi': instance.id_poi,
      'cat_convenzioni': instance.cat_convenzioni,
      'cat_areesosta': instance.cat_areesosta,
      'cat_areeservizio': instance.cat_areeservizio,
      'cat_camping': instance.cat_camping,
      'cat_attrazioni': instance.cat_attrazioni,
      'cat_allianz': instance.cat_allianz,
      'id_tipologia_poi': instance.id_tipologia_poi,
      'id_localita_poi': instance.id_localita_poi,
      'nome_poi': instance.nome_poi,
      'indirizzo_poi': instance.indirizzo_poi,
      'citta_poi': instance.citta_poi,
      'cap_poi': instance.cap_poi,
      'provincia_poi': instance.provincia_poi,
      'regione_poi': instance.regione_poi,
      'nazione_poi': instance.nazione_poi,
      'telefono_poi': instance.telefono_poi,
      'fax_poi': instance.fax_poi,
      'email_poi': instance.email_poi,
      'sitoweb_poi': instance.sitoweb_poi,
      'paginafb_poi': instance.paginafb_poi,
      'scadenza_conv_poi': instance.scadenza_conv_poi,
      'lat_poi': instance.lat_poi,
      'lon_poi': instance.lon_poi,
      'precisionegeo_poi': instance.precisionegeo_poi,
      'quota_poi': instance.quota_poi,
      'id_parchi_poi': instance.id_parchi_poi,
      'apertodal_poi': instance.apertodal_poi,
      'apertoal_poi': instance.apertoal_poi,
      'facilitazioni_poi': instance.facilitazioni_poi,
      'sconto_poi': instance.sconto_poi,
      'sconto_poi_en': instance.sconto_poi_en,
      'referenti_poi': instance.referenti_poi,
      'desc_poi': instance.desc_poi,
      'desc_poi_en': instance.desc_poi_en,
      'numeroposti_poi': instance.numeroposti_poi,
      'tariffagiorno_poi': instance.tariffagiorno_poi,
      'idsAmbienti_poi': instance.idsAmbienti_poi,
      'idsServizi_poi': instance.idsServizi_poi,
      'maxgiorni_poi': instance.maxgiorni_poi,
      'piazzola_poi': instance.piazzola_poi,
      'attrazioni_poi': instance.attrazioni_poi,
      'no_gps': instance.no_gps,
      'offline': instance.offline,
      'rev_en': instance.rev_en,
    };
